# cargo-deny configuration file
# https://embarkstudios.github.io/cargo-deny/

[graph]
# The graph table configures how the dependency graph is constructed and thus
# which crates the checks are performed over

# If true, metadata will be collected with `--all-features`. Note that this can't
# be toggled off if true, if you want to conditionally enable it (for example
# for CI), you need to pass `--all-features` on the cmd line
all-features = false

# If true, metadata will be collected with `--no-default-features`. Note that this
# can't be toggled off if true, you want to conditionally enable it (for example
# for CI), you need to pass `--no-default-features` on the cmd line
no-default-features = false

# If set, these feature will be enabled when collecting metadata. If `--features`
# is specified on the cmd line they will take precedence over this option.
features = []

# When creating the dependency graph used as the source of truth when checks are
# executed, this field can be used to prune crates from the graph, removing them
# from being checked. Multiple versions of the same crate can be matched as well,
# not just the crate name itself.
exclude = []

[advisories]
# The advisories table configures how the `cargo-deny check advisories` command behaves

# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# The lint level for security vulnerabilities
vulnerability = "deny"

# The lint level for unmaintained crates
unmaintained = "warn"

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

# The lint level for crates with security notices. Note that as of
# 2019-12-17 there are no security notice advisories in the RustSec database
notice = "warn"

# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = [
    #"RUSTSEC-0000-0000",
    #"GHSA-xxxx-xxxx-xxxx", 
]

# Threshold for security vulnerabilities, any vulnerability with a CVSS score
# lower than this value will be ignored. Note that ignored advisories will still
# output a note when they are encountered.
# * None (default) - CVSS Score 0.0
# * Low - CVSS Score 0.1 - 3.9  
# * Medium - CVSS Score 4.0 - 6.9
# * High - CVSS Score 7.0 - 8.9
# * Critical - CVSS Score 9.0 - 10.0
severity-threshold = "low"

[licenses]
# The lint level for crates which do not have a detectable license
unlicensed = "deny"

# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", 
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
]

# List of explicitly disallowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

# Lint level for when multiple versions of the same license are detected
copyleft = "warn"

# Blanket approval or denial for OSI-approved or FSF-approved licenses
# * both - The license will be approved if it is both OSI-approved AND FSF-approved
# * either - The license will be approved if it is either OSI-approved OR FSF-approved
# * osi - The license will be approved if it is OSI-approved *AND* not FSF-disapproved
# * fsf - The license will be approved if it is FSF-approved *AND* not OSI-disapproved
# * osi-only - The license will be approved if it is OSI-approved
# * fsf-only - The license will be approved if it is FSF-approved
# * neither - This predicate is ignored and the default lint level is used
allow-osi-fsf-free = "either"

# Lint level used when no other predicates are matched
# 1. License isn't in the allow or deny lists
# 2. License isn't copyleft
# 3. License isn't OSI/FSF, or allow-osi-fsf-free = "neither"
default = "deny"

# The confidence threshold for detecting a license from a license text.
# The higher the value, the more closely the license text must match the
# canonical license text of a valid SPDX license file.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 0.8

# Allow 1 or more licenses on a per-crate basis, so that particular licenses
# aren't accepted for every possible crate as with the normal allow list
exceptions = [
    # Each entry is the crate and version constraint, and its the license
    #{ allow = ["Zlib"], crate = "adler" },
]

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries.
# To see how to mark a crate as unpublished (to the official registry),
# visit https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field.
ignore = false

# One or more private registries that you might publish crates to, if a crate
# is only published to private registries, and ignore is true, the crate will
# not have its license(s) checked
registries = [
    #"https://sekretz.com/registry
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Lint level for when a crate version requirement is `*`
wildcards = "allow"

# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
# * all - both old and new versions of a crate are highlighted
# * new - only the new version of a crate is highlighted
# * old - only the old version of a crate is highlighted
# * none - no highlighting
highlight = "all"

# The default lint level for `default` features for crates that are members
# of the workspace that is being checked. This can be overridden by allowing/denying
# `default` on a crate-by-crate basis if desired.
workspace-default-features = "allow"

# The default lint level for `default` features for external crates that are not
# members of the workspace. This can be overridden by allowing/denying `default`
# on a crate-by-crate basis if desired.
external-default-features = "allow"

# List of crates that are allowed. Use with care!
allow = [
    #{ crate = "ansi_term", version = "=0.11.0" },
]

# List of crates to deny
deny = [
    # Each entry the name of a crate and a version range. If version is
    # not specified, all versions will be matched.
    #{ crate = "ansi_term", version = "=0.11.0" },
    
    # Wrapper crates can optionally be specified to allow the crate when it
    # is a direct dependency of the otherwise banned crate
    #{ crate = "ansi_term", version = "=0.11.0", wrappers = [] },
]

# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    #{ crate = "ansi_term", version = "=0.11.0" },
]

# Similarly to `skip` allows you to skip certain crates from being checked. Unlike
# `skip`, a skipped crate is removed from the dependency graph entirely and so
# will not be checked for licenses, bans, or sources.
skip-tree = [
    #{ crate = "ansi_term", version = "=0.11.0", depth = 20 },
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of URLs for allowed Git repositories
allow-git = []